name: Deploy Azure Function .NET Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  AZURE_FUNCTIONAPP_NAME: your-app-name  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.*'              # set this to the dotnet version to use

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '{{env.DOTNET_VERSION}}'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release --output {{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}/output
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.7
      with:
        # Name of the Azure Function App
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        # Path to package or folder. *.zip or a folder to deploy
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        # Publish profile (*.publishsettings) file contents with web deploy secrets
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
